### ISSUE TITLE
Use of non thread safe caching, swtich caching methods for ccv.

### ISSUE THREAD

**Issue by ghost** [BennyNottonsonSchool/spotifySort#2]

**Comment by Benny-Nottonson** [comment]
https://cachetools.readthedocs.io/en/latest/

**Comment by Benny-Nottonson** [comment]
MRU cache is probably the best bet since some playlists will have a lot of the same image in a row from adding entire albums. @cachetools.func.mru_cache(user_function)

**Comment by Benny-Nottonson** [comment]
For the other caching methods, mru might still be the best, but look into ttl and rr caching, especially for colors.
