### ISSUE TITLE
Unneeded use of PIL library, immediately converts to CV2

### ISSUE THREAD

**Issue by ghost** [BennyNottonsonSchool/spotifySort#3]

**Comment by Benny-Nottonson** [comment]
https://stackoverflow.com/questions/21061814/how-can-i-read-an-image-from-an-internet-url-in-python-cv2-scikit-image-and-mah

**Comment by Benny-Nottonson** [comment]
https://stackoverflow.com/questions/59724255/download-a-jpeg-image-given-a-url-into-numpy-array
